### ISSUE TITLE
Stop using deprecated x509.EncryptPEMBlock

### ISSUE THREAD

**Issue by k4leung4** [sigstore/scaffolding#102]
**Description**

As noted in the documentation, https://pkg.go.dev/crypto/x509#EncryptPEMBlock

`Deprecated: Legacy PEM encryption as specified in [RFC 1423](https://rfc-editor.org/rfc/rfc1423.html) is insecure by design. Since it does not authenticate the ciphertext, it is vulnerable to padding oracle attacks that can let an attacker recover the plaintext.`

https://github.com/sigstore/scaffolding/blob/main/cmd/fulcio/createcerts/main.go#L172

**Comment by vaikas** [comment]
I'd be happy to fix this, since this is for test code, I'm curious how important it is atm.
I poked a bit and having a hard time finding a suitable replacement without going to external libraries:
https://github.com/golang/go/issues/8860

**Comment by vaikas** [comment]
Yes! Makes sense. I guess we need to chase down what a suitable replacement is.

**Comment by k4leung4** [comment]
@haydentherapper 

This not used for staging or production, as it is only used when the certificate authority is set to `fileca`
For sigstore staging and production, we use `kmsca`, which does not use `createcerts` job.

**Comment by haydentherapper** [comment]
Sweet, thanks for confirming. I'm looking at dropping support for RFC1423 keys in Fulcio, so I may need to import a third-party library for PKCS#8 key generation in Scaffolding. Any concerns?

**Comment by bobcallaway** [comment]
@priyawadhwa is this done now with #1310 ?

**Comment by priyawadhwa** [comment]
I think so -- I replaced it everywhere I could, but couldn't make the change in ctlog createcerts because I don't think the ctlog supports using PKCS#8 keys
