### ISSUE TITLE
metallb config issue using setup_kind

### ISSUE THREAD

**Issue by jkhelil** [sigstore/scaffolding#1145]
**Description**
for tags prior to 0.6.17 (version supporting k8s prior to 1.26), When selecting the network for metallb config on setup_kind, this docker command returns the ipv6 subnet, and it is not safe
https://github.com/sigstore/scaffolding/blob/v0.6.17/hack/setup-kind.sh#L243
network=$(docker network inspect kind -f "{{(index .IPAM.Config 0).Subnet}}" | cut -d '.' -f1,2)

here is the issue we are facing 
``` 
rror from server (parsing address pool config: invalid CIDR "fc00:f853:ccd:e793::/64.255.1-fc00:f853:ccd:e793::/64.255.250" in pool "config": invalid IP range "fc00:f853:ccd:e793::/64.255.1-fc00:f853:ccd:e793::/64.255.250": invalid start IP "fc00:f853:ccd:e793::/64.255.1"): error when creating "./metallb-crds.yaml": admission webhook "ipaddresspoolvalidationwebhook.metallb.io" denied the request: parsing address pool config: invalid CIDR "fc00:f853:ccd:e793::/64.255.1-fc00:f853:ccd:e793::/64.255.250" in pool "config": invalid IP range "fc00:f853:ccd:e793::/64.255.1-fc00:f853:ccd:e793::/64.255.250": invalid start IP 
```

the docker command has been fixed on tag 0.7.2, but this tag is not supporting k8s prior to 1.26
network=$(docker network inspect kind | jq -r '.[0].IPAM.Config[] | select(.Subnet | test("^[0-9]+\\.")) | .Subnet' | cut -d '.' -f1,2)

We woud like to have a tag version that have the fix and supporting at least 1.26

Can we have tag version 0.6.18, with the fix ?

**Version**

**Comment by haydentherapper** [comment]
https://github.com/sigstore/scaffolding/releases/tag/v0.7.2 contains an updated metalib.

**Comment by haydentherapper** [comment]
Sorry, reread the issue. @cpanato could you take a look at backporting the fix?

**Comment by jkhelil** [comment]
thanks @haydentherapper , we need to backport it

**Comment by jkhelil** [comment]
@cpanato Would you have a look to this please (backport the fix for setup_kind). thank you

**Comment by cpanato** [comment]
backport to which version? we will do a release branch? is it not easier to move forward?

**Comment by jkhelil** [comment]
@cpanato We would need a backport supporting 1.26 and prior to 1.26, backport to 0.6.17 would be very helpful, thank you

**Comment by cpanato** [comment]
Are we sure we want that? k8s 1.26 is deprecated. I would not prefer to create a release branch to support a deprecated k8s version.

@haydentherapper can we chat about this? ping me over slack
