### ISSUE TITLE
rekor-createsecrets image is overwritten by tuf-createsercrets

### ISSUE THREAD

**Issue by vipulagarwal** [sigstore/scaffolding#1192]
**Description**

`rekor-createsecrets` image is overwritten by `tuf-createsecrets` image because they have the same file name. The packages have only one [createsecrets](https://github.com/sigstore/scaffolding/pkgs/container/scaffolding%2Fcreatesecret) image.

[`ko`](https://github.com/sigstore/scaffolding/blob/main/.ko.yaml#L189) builds the image based on the go application file name, in this case `createsecrets`

**Version**

`main`

**Comment by bobcallaway** [comment]
The options here aren't wonderful:
- rename `rekor/createsecret` to `rekor-createsecret` and `tuf/createsecret` to `tuf-createsecret`
- insert an explicit image copy somewhere in the `Makefile` to preserve the images
- create and reference a symlink (which has portability challenges)
- change `ko` arguments to change name of all published images

I'm leaning towards the first option, but it definitely feels hackish.

**Comment by vipulagarwal** [comment]
> rename rekor/createsecret to rekor-createsecret and tuf/createsecret to tuf-createsecret
I would keep the original tuf/createsecrets -> `createsecrets` as it is used in scaffolding and tuf helm charts. We can simply create rekor-createsecrets as this is not used anywhere yet (the image does not exist).

**Comment by bobcallaway** [comment]
> > rename rekor/createsecret to rekor-createsecret and tuf/createsecret to tuf-createsecret
> 
> I would keep the original `tuf/createsecrets` -> `createsecrets` as it is used in scaffolding and tuf helm charts. We can simply create `rekor-createsecrets` as this is not used anywhere yet (the image does not exist).

sg!
