### ISSUE TITLE
Make the TUF server init a consistent_snapshot repository by default

### ISSUE THREAD

**Issue by bkabrda** [sigstore/scaffolding#1236]
**Description**

As of now, the TUF server will always create a repository with `consistent_snapshot: false`. I believe it is much more useful to create a `consistent_snapshot: true` because of the benefits in updating such repositories (now that we can actually update the underlying repository thanks to https://github.com/sigstore/scaffolding/pull/1214). This can either be a one-line change if we just switch or it could be more involved if we want to keep `false` as the default and add a new flag to the server to switch to `true`. I'm ok with implementing either (obviously I have preference for just switching to `true` :wink:, but I'm not sure if that would break something else), please let me know which option sounds better.

**Comment by haydentherapper** [comment]
Yes, I think we should definitely do this, there's almost no reason to not enable this beyond some minor space saving.
