### ISSUE TITLE
gettoken deployment throws a DENIED error 

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/scaffolding#127]
**Description**

The gettoken deployment uses ` ghcr.io/chainguard-dev/apko:v0.2.2` which throws the following `denied` error:

```
Error: error processing import paths in "testdata/config/gettoken/gettoken.yaml": error resolving image references: GET https://ghcr.io/token?scope=repository%3Achainguard-dev%2Fapko%3Apull&service=ghcr.io: DENIED: denied
```

Consequently I am unable to use the scaffolding to sign images using the gettoken svc.

**Comment by vaikas** [comment]
Just saw this, is this still an issue @hectorj2f ?

**Comment by hectorj2f** [comment]
Nope, it is not happening to me anymore
