### ISSUE TITLE
light tool to create/sign (via kms) fulcio/tsa certs (ca, leaf etc)

### ISSUE THREAD

**Issue by ianhundere** [sigstore/scaffolding#1334]
**Description**

cross posting this from https://github.com/sigstore/helm-charts/issues/863 as i'm thinking something like this would best live here.

**Comment by haydentherapper** [comment]
Hey Ian, I like this idea! Would this make sense as a utility in the fulcio or timestamp-authority repositories? I want to make sure the generated certificates are conformant with the Fulcio/RFC3161 standards respectively, and if you're planning to leverage libraries from these repositories already, then maybe it'd be easiest to have them maintained under their respective repos.

**Comment by ianhundere** [comment]
hey Hayden, that definitely makes more sense.

i wasn't planning on leveraging libraries from those respective repos (tho i'm sure i could 🤔), but i'm currently using the following to create/sign certs:
```
	"context"
	"fmt"
	"math/big"
	"time"

	"crypto/x509"
	"crypto/x509/pkix"

	"encoding/json"
	"encoding/pem"
	"os"

	"go.step.sm/crypto/kms/apiv1"
	"go.step.sm/crypto/kms/awskms"
	"go.step.sm/crypto/kms/cloudkms"
	"go.step.sm/crypto/kms/azurekms"
	"go.step.sm/crypto/x509util"
```

should i go ahead and open an issue for each respective repository and pivot there for discussing this further?

btw, thanks for the quick response / feedback!

**Comment by ianhundere** [comment]
hey Hayden, that definitely makes more sense.

i wasn't planning on leveraging libraries from those respective repos, but it looks like there's some overlap.

<details>
<summary>i'm currently using the following packages/config templates to create/sign certs for fulcio and tsa</summary>

packages
```
	"context"
	"fmt"
	"math/big"
	"time"

	"crypto/x509"
	"crypto/x509/pkix"

	"encoding/json"
	"encoding/pem"
	"os"

	"go.step.sm/crypto/kms/apiv1"
	"go.step.sm/crypto/kms/awskms"
	"go.step.sm/crypto/kms/cloudkms"
	"go.step.sm/crypto/kms/azurekms"
	"go.step.sm/crypto/x509util"
```

fulcio intermediate/leaf cert template
```

{
  "subject": {
    "commonName": "https://southwest.gitlab-dedicated.com"
  },
  "issuer": {
    "commonName": "https://southwest.gitlab-dedicated.com"
  },
  "keyUsage": [
    "certSign",
    "crlSign"
  ],
  "extKeyUsage": [
    "CodeSigning"
  ],
  "basicConstraints": {
    "isCA": true,
    "maxPathLen": 0
  }
}
```
tsa intermediate/leaf cert template
```
{
    "subject": {
        "commonName": "https://blah.com"
    },
    "issuer": {
        "commonName": "https://blah.com"
    },
    "keyUsage": [
        "certSign",
        "crlSign"
    ],
    "basicConstraints": {
        "isCA": false,
        "maxPathLen": 0
    },
    "extensions": [
        {
            "id": "2.5.29.37",
            "critical": true,
            "value": {{ `{{ asn1Seq (asn1Enc "oid:1.3.6.1.5.5.7.3.8") | toJson }}` }}
        }
    ]
}
```
</details>

should i go ahead and open an issue for each respective repository and pivot there for discussing this further?

btw, thanks for the quick response / feedback!

**Comment by ianhundere** [comment]
hey Hayden, that definitely makes more sense.

i wasn't planning on leveraging libraries from those respective repos, but it looks like there's some overlap.

<details>
<summary>i'm currently using the following packages/config templates to create/sign certs for fulcio and tsa</summary>

packages
```
	"context"
	"fmt"
	"math/big"
	"time"

	"crypto/x509"
	"crypto/x509/pkix"

	"encoding/json"
	"encoding/pem"
	"os"

	"go.step.sm/crypto/kms/apiv1"
	"go.step.sm/crypto/kms/awskms"
	"go.step.sm/crypto/kms/cloudkms"
	"go.step.sm/crypto/kms/azurekms"
	"go.step.sm/crypto/x509util"
```

fulcio intermediate/leaf cert template
```

{
  "subject": {
    "commonName": "https://blah.com"
  },
  "issuer": {
    "commonName": "https://blah.com"
  },
  "keyUsage": [
    "certSign",
    "crlSign"
  ],
  "extKeyUsage": [
    "CodeSigning"
  ],
  "basicConstraints": {
    "isCA": true,
    "maxPathLen": 0
  }
}
```
tsa intermediate/leaf cert template
```
{
    "subject": {
        "commonName": "https://blah.com"
    },
    "issuer": {
        "commonName": "https://blah.com"
    },
    "keyUsage": [
        "certSign",
        "crlSign"
    ],
    "basicConstraints": {
        "isCA": false,
        "maxPathLen": 0
    },
    "extensions": [
        {
            "id": "2.5.29.37",
            "critical": true,
            "value": {{ `{{ asn1Seq (asn1Enc "oid:1.3.6.1.5.5.7.3.8") | toJson }}` }}
        }
    ]
}
```
</details>

should i go ahead and open an issue for each respective repository and pivot there for discussing this further?

btw, thanks for the quick response / feedback!

**Comment by ianhundere** [comment]
@haydentherapper / @bobcallaway 

should i create a PR in each respective repo:
- https://github.com/sigstore/fulcio
- https://github.com/sigstore/timestamp-authority

or should we have it just live in the fulcio repo w/ the expectation that someone can grab it there if needed for tsa ?

**Comment by haydentherapper** [comment]
In each repo is good with me, I'll review the PRs.

**Comment by ianhundere** [comment]
sounds good / i'll open issues there and should have PRs up by the end of the week.

**Comment by ianhundere** [comment]
closing in favor of:
- https://github.com/sigstore/fulcio/issues/1869
- https://github.com/sigstore/timestamp-authority/issues/886
