### ISSUE TITLE
sigstore/scaffolding/actions/setup@main currently broken

### ISSUE THREAD

**Issue by bcaton85** [sigstore/scaffolding#275]
**Description**

Currently working on an enhancement proposal for the Tekton Chains project. When running e2e tests for this project `sigstore/scaffolding/actions/setup@main` is called. This currently fails with the following output:
```
+ kubectl apply -f https://github.com/sigstore/scaffolding/releases/download/v0.4.0/release.yaml
error: unable to read URL "https://github.com/sigstore/scaffolding/releases/download/v0.4.0/release.yaml", server reported 404 Not Found, status code=404
```
[This action is called here.](https://github.com/tektoncd/chains/blob/main/.github/workflows/kind-e2e.yaml#L69)

**Comment by wlynch** [comment]
@vaikas looks like the change in https://github.com/sigstore/scaffolding/commit/9473e9a414c3b44ff2445a882c3ddb90da8a616b needs to be updated in the setup action - https://github.com/sigstore/scaffolding/blob/9473e9a414c3b44ff2445a882c3ddb90da8a616b/actions/setup/action.yml#L79

What's the best way to install scaffolding components now? Just kubectl apply each release-* file individually?

**Comment by wlynch** [comment]
Also need to update https://github.com/sigstore/scaffolding/blob/9473e9a414c3b44ff2445a882c3ddb90da8a616b/getting-started.md?plain=1#L34

**Comment by vaikas** [comment]
Just give me a few minutes here :)

Background (not that it solves your problem) is that we're moving to support TUF and that's a little tricky change, and I'm also trying to keep backward compatible changes going. Sorry about the breakage.

Workaround would be to specify a version in the chains. I'll fix.

**Comment by vaikas** [comment]
@bcaton85 I think this has been fixed, ok to close? Feel free to reopen if you don't think it's been fixed.
And sorry about the troubles :(

**Comment by bcaton85** [comment]
Yes fixed, no problem!

**Comment by vaikas** [comment]
Thanks for confirming @bcaton85!
