### ISSUE TITLE
Not all the tests that should be required are required for submission.

### ISSUE THREAD

**Issue by vaikas** [sigstore/scaffolding#289]
**Description**
Need to vet and update this with the correct branch protections:
https://github.com/sigstore/community/blob/main/github-sync/github-data/repositories.yaml

Currently only these are 'required':
```
        statusChecks:
          - license boilerplate check
          - DCO
          - Analyze (go)
          - Shellcheck
```

But that's not enough, need to add the proper tests. This is especially troublesome with the 'enable automerge' which could cause accidental merges even if some of the tests are failing.

**Version**
head

**Comment by cpanato** [comment]
pr to update the checks https://github.com/sigstore/community/pull/99
