### ISSUE TITLE
Terraform: OpenStack Support

### ISSUE THREAD

**Issue by Dentrax** [sigstore/scaffolding#314]
**Description**

Scaffolding project currently only supports [GCP](https://github.com/sigstore/scaffolding/tree/main/terraform) Terraform provider. We want (@developer-guy) to provision a full sigstore stack on OpenStack. Does it make sense to create a new folder called `openstack` in the `terraform` folder to drop all related modules in there?

Of course, we can extend the supporting list in the future:
* AWS
* VMware Cloud Director
* Azure
* Alibaba
* Azure
* etc.

**Comment by cpanato** [comment]
@Dentrax yes, follow the same pattern that we have for gcp :)

that sounds a nice improvement

**Comment by haydentherapper** [comment]
Going to close this as there has been no progress. If someone would like to pursue creating infrastructure for other cloud platforms, feel free to reopen this or create a new issue.
