### ISSUE TITLE
Switch Fulcio prober to hit v2 endpoints

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/scaffolding#476]
**Description**

V1 is deprecated, so we should be probing against v2.

**Comment by bobcallaway** [comment]
We're doing both: https://github.com/sigstore/scaffolding/blob/2f93986f6e45ac19ee68dd8908814e35bcff63cb/cmd/prober/endpoints.go#LL56-L67C2

**Comment by haydentherapper** [comment]
Ah thanks. This is also an issue for the write endpoint - https://github.com/sigstore/scaffolding/blob/main/cmd/prober/write.go#L55
