### ISSUE TITLE
Rekor prober traffic does not use previously generated certificate

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/scaffolding#533]
See https://github.com/sigstore/scaffolding/blob/main/cmd/prober/write.go#L157, where we generate an ephemeral key. You'll see on the write path for Fulcio, we fetch a certificate which is then discarded. The Rekor write path generates an ephemeral key and uploads that to Rekor. This tests Fulcio and Rekor independently, but I see two issues:
* This is not truly an e2e test, because there could be an issue with certificate upload in Rekor
* There is no way to distinguish prober entries in Rekor from other key-based entries without looking at request headers

I propose that we use the certificate generated from Fulcio and upload it to Rekor (if it's not available, let's say because you're not probing fulcio, then generate an ephemeral key)

**Comment by bobcallaway** [comment]
is this done now @haydentherapper ?
